# Generated by Django 4.2.16 on 2026-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('HOMES', 'Homes'), ('EXPERIENCES', 'Experiences'), ('SERVICES', 'Services')], default='HOMES', max_length=20),
        ),
    ]
